export default {
	login: 'AkhmaevM',
	id: 2136245,
	node_id: 'U_kgDOBaVtWA',
	avatar_url: 'https://avatars.githubusercontent.com/u/94727512?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/AkhmaevM',
	html_url: 'https://github.com/AkhmaevM',
	followers_url: '',
	following_url: '',
	gists_url: 'https://api.github.com/users/AkhmaevM/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/AkhmaevM/starred{/owner}{/repo}',
	subscriptions_url: '',
	organizations_url: '',
	repos_url: '',
	events_url: 'https://api.github.com/users/AkhmaevM/events{/privacy}',
	received_events_url: 'https://api.github.com/users/AkhmaevM/received_events',
	type: 'User',
	site_admin: false,
	name: 'Magomed Akhmaev',
	company: '',
	blog: '',
	location: '',
	email: null,
	hireable: null,
	bio: '',
	twitter_username: '',
	public_repos: '',
	public_gists: '',
	followers: '',
	following: '',
	created_at: '',
	updated_at: '',
};


